LangString addOrReinstall ${LANG_DANISH} "Tilføj eller geninstallér dele"
LangString alreadyInstalled ${LANG_DANISH} "Allerede installeret"
LangString alreadyInstalledLong ${LANG_DANISH} "${PRODUCTNAME} ${VERSION} er allerede installeret. Vælg, hvad du vil gøre, og klik på Næste."
LangString appRunning ${LANG_DANISH} "{{product_name}} kører. Luk programmet, og prøv igen."
LangString appRunningOkKill ${LANG_DANISH} "{{product_name}} kører.$\nKlik på OK for at lukke det."
LangString chooseMaintenanceOption ${LANG_DANISH} "Vælg, hvad du vil gøre."
LangString choowHowToInstall ${LANG_DANISH} "Vælg, hvordan ${PRODUCTNAME} skal installeres."
LangString createDesktop ${LANG_DANISH} "Lav en genvej på skrivebordet"
LangString dontUninstall ${LANG_DANISH} "Afinstallér ikke"
LangString dontUninstallDowngrade ${LANG_DANISH} "Afinstallér ikke (en ældre version kan ikke installeres oven i en nyere)"
LangString failedToKillApp ${LANG_DANISH} "{{product_name}} kunne ikke lukkes. Luk programmet, og prøv igen."
LangString installingWebview2 ${LANG_DANISH} "Installerer WebView2 …"
LangString newerVersionInstalled ${LANG_DANISH} "Der er allerede installeret en nyere version af ${PRODUCTNAME}. Vil du alligevel have den ældre, så afinstallér den nye først. Vælg, hvad du vil gøre, og klik på Næste."
LangString older ${LANG_DANISH} "ældre"
LangString olderOrUnknownVersionInstalled ${LANG_DANISH} "Der er installeret en $R4 version af ${PRODUCTNAME}. Det er bedst at afinstallere den først. Vælg, hvad du vil gøre, og klik på Næste."
LangString silentDowngrades ${LANG_DANISH} "En ældre version kan ikke installeres uden vindue. Brug den almindelige installation i stedet.$\n"
LangString unableToUninstall ${LANG_DANISH} "Programmet kunne ikke afinstalleres."
LangString uninstallApp ${LANG_DANISH} "Afinstallér ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_DANISH} "Afinstallér før installation"
LangString unknown ${LANG_DANISH} "ukendt"
LangString webview2AbortError ${LANG_DANISH} "WebView2 kunne ikke installeres, og programmet kan ikke køre uden. Start installationen igen."
LangString webview2DownloadError ${LANG_DANISH} "WebView2 kunne ikke hentes: $0"
LangString webview2DownloadSuccess ${LANG_DANISH} "WebView2 er hentet"
LangString webview2Downloading ${LANG_DANISH} "Henter WebView2 …"
LangString webview2InstallError ${LANG_DANISH} "WebView2 kunne ikke installeres (fejlkode $1)"
LangString webview2InstallSuccess ${LANG_DANISH} "WebView2 er installeret"
LangString deleteAppData ${LANG_DANISH} "Slet også indstillinger, versioner og backup"
