// Egne korte beskrivelser og arbejdsspørgsmål. Kilderne beskriver metoderne, ikke faste krav til teksten.
export type ModelRole = { id: string; name: string; question: string };
export type NarrativeModel = { id: string; name: string; groups: string[]; description: string; source: string; roles: ModelRole[] };
export const MODEL_GROUPS = ["Journalistik og nonfiktion", "Fiktion og erindring", "Videnskab og faglig formidling", "Præsentationer og argumentation"];
const role = (id: string, name: string, question: string): ModelRole => ({ id, name, question });
export const NARRATIVE_MODELS: NarrativeModel[] = [
  { id: "news", name: "Nyhedstrekanten", groups: [MODEL_GROUPS[0]], description: "Det vigtigste først. God til nyheder og kort orientering.", source: "https://mediekonkurrencen.dk/nyhedstrekanten/", roles: [role("point", "Hovedpointe", "Hvad skal læseren vide, selv hvis læsningen stopper her?"), role("evidence", "Dokumentation", "Hvilke oplysninger underbygger hovedpointen?"), role("context", "Baggrund", "Hvilken sammenhæng har læseren brug for?")] },
  { id: "hey-you-see-so", name: "Hey–You–See–So", groups: [MODEL_GROUPS[0], MODEL_GROUPS[3]], description: "Fang interessen, vis relevansen, fold emnet ud og vis betydningen.", source: "https://mediekonkurrencen.dk/hey-you-see-so-modellen/", roles: [role("hey", "Indgang", "Hvad vækker interesse for emnet?"), role("you", "Relevans", "Hvem berører det, og hvorfor?"), role("see", "Udfoldelse", "Hvad viser kilderne og eksemplerne?"), role("so", "Betydning", "Hvad følger af det, læseren nu ved?")] },
  { id: "feature", name: "Scene og perspektiv", groups: [MODEL_GROUPS[0], MODEL_GROUPS[2]], description: "En konkret indgang åbner en større sammenhæng. Inspireret af feature og nut graf.", source: "https://www.poynter.org/archive/2003/the-nut-graf-part-i/", roles: [role("scene", "Konkret indgang", "Hvilken dokumenteret situation åbner historien?"), role("perspective", "Perspektiv", "Hvad viser historien ud over den enkelte person?"), role("development", "Uddybning", "Hvordan hænger eksempler og dokumentation sammen?"), role("ending", "Afrunding", "Hvilket billede eller spørgsmål bliver hos læseren?")] },
  { id: "drawers", name: "Kommodemodellen", groups: [MODEL_GROUPS[0], MODEL_GROUPS[2]], description: "En åbning og flere selvstændige dele. Velegnet til længere baggrund og forklaring.", source: "https://mediekonkurrencen.dk/kommodemodellen/", roles: [role("opening", "Åbning", "Hvad lover begyndelsen, at teksten vil forklare?"), role("drawer", "En ny del", "Hvad tilfører denne del, som de andre ikke gør?"), role("ending", "Afslutning", "Hvordan samler slutningen trådene?")] },
  { id: "fish", name: "Fisken", groups: [MODEL_GROUPS[0]], description: "Fangende begyndelse, udfoldelse og en slutning med efterklang. Til reportage.", source: "https://mediekonkurrencen.dk/fiskemodellen/", roles: [role("head", "Åbning", "Hvilken observation trækker læseren ind?"), role("body", "Udfoldelse", "Hvad oplever og lærer læseren undervejs?"), role("tail", "Efterklang", "Hvilken detalje giver slutningen vægt?")] },
  { id: "apus", name: "APUS", groups: [MODEL_GROUPS[0]], description: "Anslag, præsentation, uddybning og slutning. Fra nordisk radio og tv, her tilpasset skrift.", source: "https://ndla.no/r/medie--og-informasjonskunnskap-2/analyse-av-nyhetsfortellinger/110954fcc5/17427", roles: [role("opening", "Anslag", "Hvilken konkret indgang vækker interesse?"), role("presentation", "Præsentation", "Hvem og hvad skal læseren kende?"), role("development", "Uddybning", "Hvordan udfolder forløbet sig?"), role("ending", "Slutning", "Hvad står tilbage efter forløbet?")] },
  { id: "hourglass", name: "Timeglasset", groups: [MODEL_GROUPS[0]], description: "Nyheden først, derefter en overgang til et kronologisk forløb.", source: "https://www.poynter.org/reporting-editing/2003/the-hourglass-serving-the-news-serving-the-reader/", roles: [role("news", "Nyhedsresumé", "Hvad er det vigtigste udfald?"), role("turn", "Overgang", "Hvordan fører teksten læseren tilbage til begyndelsen?"), role("sequence", "Forløb", "Hvad skete i hvilken rækkefølge?")] },
  { id: "three-acts", name: "Tre akter", groups: [MODEL_GROUPS[1], MODEL_GROUPS[0]], description: "Etablering, udvikling og afgørelse. Til fiktion og dokumenterede personforløb.", source: "https://www.filminstitutet.se/sv/fa-kunskap-om-film/filmpedagogik/filmlexikon/analysmodeller/dramaturgiska-modellen/treaktsmodellen/", roles: [role("setup", "Etablering", "Hvem vil noget, og hvad står på spil?"), role("confrontation", "Udvikling", "Hvilken modstand ændrer personens muligheder?"), role("resolution", "Afgørelse", "Hvad bliver udfaldet, og hvad har ændret sig?")] },
  { id: "dramatic", name: "Berettermodellen", groups: [MODEL_GROUPS[1]], description: "Syv mulige faser til et dramatisk forløb. Brug dem frit uden faste længdekrav.", source: "https://www.dfi.dk/grundskolen/filmsprog/anslag", roles: [role("opening", "Anslag", "Hvad åbner fortællingens verden?"), role("presentation", "Præsentation", "Hvem og hvad lærer læseren at kende?"), role("development", "Uddybning", "Hvad gør konflikten tydelig?"), role("commitment", "Ingen vej tilbage", "Hvilken handling ændrer mulighederne?"), role("escalation", "Optrapning", "Hvordan bliver modstanden større?"), role("climax", "Klimaks", "Hvor bliver konflikten afgjort?"), role("ending", "Udtoning", "Hvad er følgerne af afgørelsen?")] },
  { id: "imrad", name: "IMRaD", groups: [MODEL_GROUPS[2]], description: "Indledning, metode, resultater og diskussion. Til original forskning, med plads til fagets egne krav.", source: "https://icmje.org/recommendations/browse/manuscript-preparation/preparing-for-submission.html", roles: [role("introduction", "Indledning", "Hvilket spørgsmål undersøger arbejdet, og hvorfor?"), role("methods", "Metode", "Hvordan blev undersøgelsen gennemført?"), role("results", "Resultater", "Hvad viste undersøgelsen?"), role("discussion", "Diskussion", "Hvad betyder resultaterne, og hvilke begrænsninger har de?")] },
  { id: "toulmin", name: "Toulmins argumentation", groups: [MODEL_GROUPS[2], MODEL_GROUPS[3]], description: "Undersøg forbindelsen mellem påstand og belæg. Roller kan optræde flere gange og i fri rækkefølge.", source: "https://owl.purdue.edu/owl/general_writing/academic_writing/historical_perspectives_on_argumentation/toulmin_argument.html", roles: [role("claim", "Påstand", "Hvad argumenterer teksten for?"), role("grounds", "Belæg", "Hvilke konkrete oplysninger støtter påstanden?"), role("warrant", "Forbindelse", "Hvorfor støtter netop disse oplysninger påstanden?"), role("backing", "Støtte", "Hvad understøtter forbindelsen?"), role("qualifier", "Forbehold", "Hvor sikkert og hvor bredt gælder argumentet?"), role("rebuttal", "Indvending", "Hvilke modargumenter skal behandles?")] },
  { id: "assertion-evidence", name: "Pointe og belæg", groups: [MODEL_GROUPS[3], MODEL_GROUPS[2]], description: "Byg oplægget om budskaber med konkret dokumentation. Tilpasset assertion–evidence til manuskripter.", source: "https://www.assertion-evidence.org/tutorial.html", roles: [role("question", "Spørgsmål", "Hvad skal publikum forstå eller kunne bagefter?"), role("assertion", "Pointe", "Hvilket budskab skal denne del bære?"), role("evidence", "Belæg", "Hvilket eksempel, billede eller resultat viser pointen?"), role("conclusion", "Afslutning", "Hvad skal publikum tage med sig?")] },
];
export function narrativeModel(id: string): NarrativeModel | undefined { return NARRATIVE_MODELS.find(m => m.id === id); }
